--------------------------------------------------------
-- Archivo creado  - jueves-marzo-26-2020   
--------------------------------------------------------
DROP SEQUENCE "USER_ESCOM"."SEQ_GEN_IDENTITY";
DROP SEQUENCE "USER_ESCOM"."TBL_ACTIVITY_SEQ";
DROP SEQUENCE "USER_ESCOM"."TBL_ANNEX_SEQ";
DROP SEQUENCE "USER_ESCOM"."TBL_ANNEX_VERSION_SEQ";
DROP SEQUENCE "USER_ESCOM"."TBL_COMMENTARY_SEQ";
DROP SEQUENCE "USER_ESCOM"."TBL_CONDITION_SEQ";
DROP SEQUENCE "USER_ESCOM"."TBL_DOCUMENT_SEQ";
DROP SEQUENCE "USER_ESCOM"."TBL_DOCUMENT_VERSION_SEQ";
DROP SEQUENCE "USER_ESCOM"."TBL_PROCESS_SEQ";
DROP SEQUENCE "USER_ESCOM"."TBL_PROGRAM_SEQ";
DROP SEQUENCE "USER_ESCOM"."TBL_USER_CONDITION_SEQ";
DROP TABLE "USER_ESCOM"."TBL_ACTIVITY" cascade constraints;
DROP TABLE "USER_ESCOM"."TBL_ANNEX" cascade constraints;
DROP TABLE "USER_ESCOM"."TBL_ANNEX_VERSION" cascade constraints;
DROP TABLE "USER_ESCOM"."TBL_COMMENTARY" cascade constraints;
DROP TABLE "USER_ESCOM"."TBL_CONDITION" cascade constraints;
DROP TABLE "USER_ESCOM"."TBL_DOCUMENT" cascade constraints;
DROP TABLE "USER_ESCOM"."TBL_DOCUMENT_VERSION" cascade constraints;
DROP TABLE "USER_ESCOM"."TBL_PROCESS" cascade constraints;
DROP TABLE "USER_ESCOM"."TBL_PROGRAM" cascade constraints;
DROP TABLE "USER_ESCOM"."TBL_USER_CONDITION" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence SEQ_GEN_IDENTITY
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."SEQ_GEN_IDENTITY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 98 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_ACTIVITY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."TBL_ACTIVITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_ANNEX_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."TBL_ANNEX_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_ANNEX_VERSION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."TBL_ANNEX_VERSION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_COMMENTARY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."TBL_COMMENTARY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_CONDITION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."TBL_CONDITION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_DOCUMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."TBL_DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_DOCUMENT_VERSION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."TBL_DOCUMENT_VERSION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_PROCESS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."TBL_PROCESS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_PROGRAM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."TBL_PROGRAM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_USER_CONDITION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_ESCOM"."TBL_USER_CONDITION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_ACTIVITY
--------------------------------------------------------

  CREATE TABLE "USER_ESCOM"."TBL_ACTIVITY" 
   (	"PK_ACT_ID" NUMBER, 
	"ACT_NAME" VARCHAR2(200 BYTE), 
	"ACT_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"ACT_INFORMATION" CLOB, 
	"ACT_STATE" NUMBER, 
	"FK_ACT_CONDITION" NUMBER, 
	"FK_ACT_ANNEX" NUMBER, 
	"ACT_TYPE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("ACT_INFORMATION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TBL_ANNEX
--------------------------------------------------------

  CREATE TABLE "USER_ESCOM"."TBL_ANNEX" 
   (	"PK_AX_ID" NUMBER, 
	"AX_KEYWORDS" VARCHAR2(200 BYTE), 
	"AX_DESCRIPTION" VARCHAR2(500 BYTE), 
	"AX_NAME" VARCHAR2(200 BYTE), 
	"FK_AX_PROGRAM" NUMBER, 
	"AX_STATE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_ANNEX_VERSION
--------------------------------------------------------

  CREATE TABLE "USER_ESCOM"."TBL_ANNEX_VERSION" 
   (	"PK_AV_ID" NUMBER, 
	"AV_DATE" DATE, 
	"AV_LOCATION" VARCHAR2(300 BYTE), 
	"AV_STATE" NUMBER, 
	"FK_AV_ANNEX" NUMBER, 
	"AV_DESCRIPTION" VARCHAR2(500 BYTE), 
	"FK_AV_USER" NUMBER, 
	"AV_VERSION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_COMMENTARY
--------------------------------------------------------

  CREATE TABLE "USER_ESCOM"."TBL_COMMENTARY" 
   (	"PK_COM_ID" NUMBER, 
	"COM_MESSAGE" VARCHAR2(1000 BYTE), 
	"COM_DATE" DATE, 
	"COM_STATE" NUMBER, 
	"FK_COM_USER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_CONDITION
--------------------------------------------------------

  CREATE TABLE "USER_ESCOM"."TBL_CONDITION" 
   (	"PK_CON_ID" NUMBER, 
	"CON_NAME" VARCHAR2(200 BYTE), 
	"CON_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"CON_STATE" NUMBER, 
	"FK_CON_PROCESS" NUMBER, 
	"CON_START_DATE" DATE, 
	"CON_FINAL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "USER_ESCOM"."TBL_DOCUMENT" 
   (	"PK_DOC_ID" NUMBER, 
	"DOC_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"DOC_TYPE" VARCHAR2(200 BYTE), 
	"DOC_STATE" NUMBER, 
	"FK_DOC_PROGRAM" NUMBER, 
	"FK_DOC_USER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_DOCUMENT_VERSION
--------------------------------------------------------

  CREATE TABLE "USER_ESCOM"."TBL_DOCUMENT_VERSION" 
   (	"PK_DV_ID" NUMBER, 
	"DV_DESCRIPTION" VARCHAR2(500 BYTE), 
	"DV_VERSION" NUMBER, 
	"DV_LOCATION" VARCHAR2(300 BYTE), 
	"DV_STATE" NUMBER, 
	"FK_DV_DOCUMENT" NUMBER, 
	"DV_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_PROCESS
--------------------------------------------------------

  CREATE TABLE "USER_ESCOM"."TBL_PROCESS" 
   (	"PK_PRC_ID" NUMBER, 
	"PRC_NAME" VARCHAR2(200 BYTE), 
	"PRC_DESCRIPTION" VARCHAR2(500 BYTE), 
	"FK_PRC_DOCUMENT" NUMBER, 
	"PRC_STATE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_PROGRAM
--------------------------------------------------------

  CREATE TABLE "USER_ESCOM"."TBL_PROGRAM" 
   (	"PK_PRO_ID" NUMBER, 
	"PRO_NAME" VARCHAR2(200 BYTE), 
	"PRO_LEVEL_EDUCATION" VARCHAR2(200 BYTE), 
	"PRO_METHODOLOGY" VARCHAR2(200 BYTE), 
	"PRO_ACADEMIC_CREDITS" NUMBER, 
	"PRO_DURATION" NUMBER, 
	"PRO_INSTITUTION" VARCHAR2(200 BYTE), 
	"PRO_CAMPUS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_USER_CONDITION
--------------------------------------------------------

  CREATE TABLE "USER_ESCOM"."TBL_USER_CONDITION" 
   (	"PK_UC_ID" NUMBER, 
	"FK_UC_USER" NUMBER, 
	"FK_UC_CONDITION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into USER_ESCOM.TBL_ACTIVITY
SET DEFINE OFF;
Insert into USER_ESCOM.TBL_ACTIVITY (PK_ACT_ID,ACT_NAME,ACT_DESCRIPTION,ACT_STATE,FK_ACT_CONDITION,FK_ACT_ANNEX,ACT_TYPE) values ('18','nueva','lista ','1','8',null,'1');
Insert into USER_ESCOM.TBL_ACTIVITY (PK_ACT_ID,ACT_NAME,ACT_DESCRIPTION,ACT_STATE,FK_ACT_CONDITION,FK_ACT_ANNEX,ACT_TYPE) values ('38','otra','nueva ','1','8',null,'1');
Insert into USER_ESCOM.TBL_ACTIVITY (PK_ACT_ID,ACT_NAME,ACT_DESCRIPTION,ACT_STATE,FK_ACT_CONDITION,FK_ACT_ANNEX,ACT_TYPE) values ('39','prueba','prueba ','1','8',null,'1');
Insert into USER_ESCOM.TBL_ACTIVITY (PK_ACT_ID,ACT_NAME,ACT_DESCRIPTION,ACT_STATE,FK_ACT_CONDITION,FK_ACT_ANNEX,ACT_TYPE) values ('40','hola','como ','1','8',null,'1');
Insert into USER_ESCOM.TBL_ACTIVITY (PK_ACT_ID,ACT_NAME,ACT_DESCRIPTION,ACT_STATE,FK_ACT_CONDITION,FK_ACT_ANNEX,ACT_TYPE) values ('79','etsasa','asdasdasd','1','8',null,'1');
REM INSERTING into USER_ESCOM.TBL_ANNEX
SET DEFINE OFF;
REM INSERTING into USER_ESCOM.TBL_ANNEX_VERSION
SET DEFINE OFF;
REM INSERTING into USER_ESCOM.TBL_COMMENTARY
SET DEFINE OFF;
REM INSERTING into USER_ESCOM.TBL_CONDITION
SET DEFINE OFF;
Insert into USER_ESCOM.TBL_CONDITION (PK_CON_ID,CON_NAME,CON_DESCRIPTION,CON_STATE,FK_CON_PROCESS,CON_START_DATE,CON_FINAL_DATE) values ('8','Denominacion ','prueba','1','7',to_date('09/03/20','DD/MM/RR'),to_date('02/03/20','DD/MM/RR'));
REM INSERTING into USER_ESCOM.TBL_DOCUMENT
SET DEFINE OFF;
Insert into USER_ESCOM.TBL_DOCUMENT (PK_DOC_ID,DOC_DESCRIPTION,DOC_TYPE,DOC_STATE,FK_DOC_PROGRAM,FK_DOC_USER) values ('3','nuevo documento','documento','1','2','0');
Insert into USER_ESCOM.TBL_DOCUMENT (PK_DOC_ID,DOC_DESCRIPTION,DOC_TYPE,DOC_STATE,FK_DOC_PROGRAM,FK_DOC_USER) values ('81',null,'asadsd','-1','2','0');
Insert into USER_ESCOM.TBL_DOCUMENT (PK_DOC_ID,DOC_DESCRIPTION,DOC_TYPE,DOC_STATE,FK_DOC_PROGRAM,FK_DOC_USER) values ('82','sadasdasdasdsd
asdasdasd','asdasd','-1','2','0');
REM INSERTING into USER_ESCOM.TBL_DOCUMENT_VERSION
SET DEFINE OFF;
REM INSERTING into USER_ESCOM.TBL_PROCESS
SET DEFINE OFF;
Insert into USER_ESCOM.TBL_PROCESS (PK_PRC_ID,PRC_NAME,PRC_DESCRIPTION,FK_PRC_DOCUMENT,PRC_STATE) values ('7','institucional','descripcion','3','1');
Insert into USER_ESCOM.TBL_PROCESS (PK_PRC_ID,PRC_NAME,PRC_DESCRIPTION,FK_PRC_DOCUMENT,PRC_STATE) values ('80','programa','programa','3','-1');
REM INSERTING into USER_ESCOM.TBL_PROGRAM
SET DEFINE OFF;
Insert into USER_ESCOM.TBL_PROGRAM (PK_PRO_ID,PRO_NAME,PRO_LEVEL_EDUCATION,PRO_METHODOLOGY,PRO_ACADEMIC_CREDITS,PRO_DURATION,PRO_INSTITUTION,PRO_CAMPUS) values ('2','Ingeneria de sistemas','Pregrado','Presencial','120','10','Universidad de cundinamarca','Facatativa');
REM INSERTING into USER_ESCOM.TBL_USER_CONDITION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger TBL_ACTIVITY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_ESCOM"."TBL_ACTIVITY_TRG" 
BEFORE INSERT ON TBL_ACTIVITY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER_ESCOM"."TBL_ACTIVITY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_ANNEX_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_ESCOM"."TBL_ANNEX_TRG" 
BEFORE INSERT ON TBL_ANNEX 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_AX_ID IS NULL THEN
      SELECT TBL_ANNEX_SEQ.NEXTVAL INTO :NEW.PK_AX_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER_ESCOM"."TBL_ANNEX_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_ANNEX_VERSION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_ESCOM"."TBL_ANNEX_VERSION_TRG" 
BEFORE INSERT ON TBL_ANNEX_VERSION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_AV_ID IS NULL THEN
      SELECT TBL_ANNEX_VERSION_SEQ.NEXTVAL INTO :NEW.PK_AV_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER_ESCOM"."TBL_ANNEX_VERSION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_COMMENTARY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_ESCOM"."TBL_COMMENTARY_TRG" 
BEFORE INSERT ON TBL_COMMENTARY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_COM_ID IS NULL THEN
      SELECT TBL_COMMENTARY_SEQ.NEXTVAL INTO :NEW.PK_COM_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER_ESCOM"."TBL_COMMENTARY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_CONDITION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_ESCOM"."TBL_CONDITION_TRG" 
BEFORE INSERT ON TBL_CONDITION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_CON_ID IS NULL THEN
      SELECT TBL_CONDITION_SEQ.NEXTVAL INTO :NEW.PK_CON_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER_ESCOM"."TBL_CONDITION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_DOCUMENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_ESCOM"."TBL_DOCUMENT_TRG" 
BEFORE INSERT ON TBL_DOCUMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_DOC_ID IS NULL THEN
      SELECT TBL_DOCUMENT_SEQ.NEXTVAL INTO :NEW.PK_DOC_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER_ESCOM"."TBL_DOCUMENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_DOCUMENT_VERSION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_ESCOM"."TBL_DOCUMENT_VERSION_TRG" 
BEFORE INSERT ON TBL_DOCUMENT_VERSION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_DV_ID IS NULL THEN
      SELECT TBL_DOCUMENT_VERSION_SEQ.NEXTVAL INTO :NEW.PK_DV_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER_ESCOM"."TBL_DOCUMENT_VERSION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_PROCESS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_ESCOM"."TBL_PROCESS_TRG" 
BEFORE INSERT ON TBL_PROCESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_PRC_ID IS NULL THEN
      SELECT TBL_PROCESS_SEQ.NEXTVAL INTO :NEW.PK_PRC_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER_ESCOM"."TBL_PROCESS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_PROGRAM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_ESCOM"."TBL_PROGRAM_TRG" 
BEFORE INSERT ON TBL_PROGRAM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_PRO_ID IS NULL THEN
      SELECT TBL_PROGRAM_SEQ.NEXTVAL INTO :NEW.PK_PRO_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER_ESCOM"."TBL_PROGRAM_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_USER_CONDITION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_ESCOM"."TBL_USER_CONDITION_TRG" 
BEFORE INSERT ON TBL_USER_CONDITION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK_UC_ID IS NULL THEN
      SELECT TBL_USER_CONDITION_SEQ.NEXTVAL INTO :NEW.PK_UC_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "USER_ESCOM"."TBL_USER_CONDITION_TRG" ENABLE;
